    echo "sinny    l2tpd    890503       *" >> /etc/ppp/chap-secrets
	echo "dell    l2tpd    dell       *" >> /etc/ppp/chap-secrets
    echo "mix    l2tpd    mix       *" >> /etc/ppp/chap-secrets
    echo "mi    l2tpd    mi      *" >> /etc/ppp/chap-secrets
	echo "ipad    l2tpd    ipad       *" >> /etc/ppp/chap-secrets
    echo "joyce    l2tpd    shijue       *" >> /etc/ppp/chap-secrets
    echo "chaochao    l2tpd    aaa123321       *" >> /etc/ppp/chap-secrets
	echo "alicia    l2tpd   tanyalin       *" >> /etc/ppp/chap-secrets
    echo "cindy    l2tpd    tangxueying       *" >> /etc/ppp/chap-secrets
    echo "cathy    l2tpd    wangzhe       *" >> /etc/ppp/chap-secrets
	echo "cathymac    l2tpd    wangzhe       *" >> /etc/ppp/chap-secrets
    echo "sunny    l2tpd    wangzhaokun       *" >> /etc/ppp/chap-secrets
    echo "doreen    l2tpd    huwenchao       *" >> /etc/ppp/chap-secrets
	echo "boxuan    l2tpd    zhangboxuan       *" >> /etc/ppp/chap-secrets
    echo "teresa    l2tpd    liumengxin       *" >> /etc/ppp/chap-secrets
    echo "nina    l2tpd    nijiayan       *" >> /etc/ppp/chap-secrets
	echo "keira    l2tpd    sunwen       *" >> /etc/ppp/chap-secrets
    echo "yvonne    l2tpd    zhaoyueru       *" >> /etc/ppp/chap-secrets
    echo "vincent    l2tpd    wuyi       *" >> /etc/ppp/chap-secrets
	echo "moto    l2tpd    ligongyan       *" >> /etc/ppp/chap-secrets